
dataset:
  dir: ./data
  start_idx: 0
  end_idx: 50
  resolution:
  - 128
  - 128
  use_xyz: 1
  use_rots: 1
  use_scale: 1
  use_opacity: 1
  use_color: 1
  use_motion: 0

output:
  dir: ./output
  save_interval: 10
  
training:
  seed: 0
  batch_size: 12
  epochs: 2000
  num_workers: 0
  lr: 0.0004
  warmup: 10000
  decay_rate: 0.5
  decay_steps: 100000
  
cnn:
  gs_pos_embed: false
  encode_gs: false
  hid_dim: 64

attention:
  use_all_gs: true
  num_slots: 10
  num_iters: 3
